config/routes.rb
Rails.application.routes.draw do

  resources :attachments
  resources :users
  get "auth/login", to: "auth#login", as: "login"
  post "auth/authentificate"
  post "auth/logout", as: "logout"
  get  "auth/logout", as: "get_logout"

  resources :menu

  root 'menu#index'
  resources :groups
  post "groups/:id/add", to: "users#add", as: "add_to_group"
  get 'groups_execute' => 'groups#execute'
  get 'groups_commit'  => 'groups#commit', as: :groups_commit

  get "timetables", to: "timetables#index", as: "timetables"
  post "events/move"
  get "timetables/init"
  post "timetables/show"
  get "timetables/:id/to_json", to: "timetables#to_json", as: "to_json_timetable"
  get "timetables/paste"
  post "timetables/:id/from_json", to: "timetables#from_json", as: "from_json_timetable"
  get 'timetables_execute' => 'timetables#execute'
  get 'timetables_commit'  => 'timetables#commit', as: :timetables_commit
  resources :timetables
  resources :schedule
  resources :events
  resources :timetable_templates

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_one :timetable, dependent: :destroy
end

app/controllers/groups_controller.rb
#coding: utf-8
class GroupsController < ApplicationController
  helper :all
  layout 'menu'
  def index
    groups = @user.groups
    @groups = []
    groups.each do |group|
      @groups << {"number" => group.name,
                  "show_ref" => "<a href=\"#{group_path(group)}\">Просмотр</a>",
                  "edit_ref" => "<a href=\"#{edit_group_path(group)}\">Редактировать</a>"}
    end
  end

  def show
    @group = Group.find(params[:id])
    @users = []
    @group.users.each do |user|
      @users << {"fio" => "<a href=\"#{group_user_path(@group, user)}\">#{user.fio}</a>",
                    "login" => user.login}
    end
  end

  def new
  end

  def create
    group = Group.new(name: params[:number])
    group.create_timetable
    group.timetable.user_id = @user.id
    group.timetable.group_number = group.name
    group.timetable.save
    group.users << @user
    group.save
    redirect_to edit_group_path(group)
  end

  def edit
    @group = Group.find(params[:id])
    @users = []
    @group.users.each do |user|
      @users << {"fio" => user.fio,
                    "login" => user.login,
                    "delete" => ""}
    end
    @users << {"fio" =>'<input type="textbox" name="fio" placeholder="Логин" class="form-control"/>',
      "login" => '<input type="submit" value="Добавить" class="btn btn-primary">',
      "delete" => ""}
  end

  def update
    group = Group.find(params[:id])
    group.name = params[:number]
    group.save
    redirect_to groups_path(group)
  end

end

app/views/groups/_group.html.erb
<li>Название: <%= link_to group.name, schedule_path(Timetable.find_by(group_id: group.id)), method: :get%> <%= Timetable.find_by(group_id: group.id).permit ? 'Публичное': 'Приватное' %></li>

app/views/groups/edit.html.erb
<% content_for(:head) do %>
  <title>Группа <%= @group.name %></title>
<% end %>
<div class="row">
  <div class="col-lg-5"></div>
  <div class="col-lg-2 aling-center">
    <%= form_tag group_path, method: "PUT" do %>
      <%= label_tag :number, "Название группы:" %>
      <%= text_field_tag :number, @group.name, class: 'form-control' %><br/>
      <%= submit_tag "Сохранить", class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="col-lg-5"></div>
</div>
<%= form_tag "add", method: "POST" do %>
  <%= display_standard_table([{name: "fio", display_name: "ФИО"},
                              {name: "login", display_name: "Логин"},
                              {name: "delete", display_name: ""}], @users) %>
<% end %>

app/views/groups/index.html.erb
<% content_for(:head) do %>
  <title>Группы</title>
<% end %>

  <%= link_to "Создать группу", new_group_path, class: 'btn btn-primary align-center' %>
<br>
<br>

<% if session[:planning_task_id] != nil %>
    <li>
      <%= link_to 'Завершить задачу планировщика', :action => "commit"%>
    </li>
<% end %>


<%= display_standard_table([{name: "number", display_name: "Номер"},
                            {name: "show_ref", display_name: "Просмотр"},
                            {name: "edit_ref", display_name: "Редактировать"}],
                          @groups) %>

app/views/groups/new.html.erb
<% content_for(:head) do %>
  <title>Новая группа</title>
<% end %>

<div class="col-lg-5"></div>
<div class="col-lg-2 aling-center">
  <%= form_tag groups_path, method: "POST" do %>
    <div class="form-group">
      <%= label_tag :number, "Название группы:" %>
      <%= text_field_tag :number, nil, class: 'form-control' %><br/>
      <%= submit_tag "Создать", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<div class="col-lg-5"></div>

app/views/groups/show.html.erb
<% content_for(:head) do %>
  <title>Группа <%= @group.name %></title>
<% end %>

<%= content_tag :span, "Название группы:" %>
<%= content_tag :span, @group.name, class: 'form-control'%><br/>

<%= display_standard_table([{name: "fio", display_name: "ФИО"},
                            {name: "login", display_name: "Логин"}



                           ], @users) %>