config/routes.rb
Rails.application.routes.draw do

  resources :attachments
  resources :users
  get "auth/login", to: "auth#login", as: "login"
  post "auth/authentificate"
  post "auth/logout", as: "logout"
  get  "auth/logout", as: "get_logout"

  resources :menu

  root 'menu#index'
  resources :groups
  post "groups/:id/add", to: "users#add", as: "add_to_group"
  get 'groups_execute' => 'groups#execute'
  get 'groups_commit'  => 'groups#commit', as: :groups_commit

  get "timetables", to: "timetables#index", as: "timetables"
  post "events/move"
  get "timetables/init"
  post "timetables/show"
  get "timetables/:id/to_json", to: "timetables#to_json", as: "to_json_timetable"
  get "timetables/paste"
  post "timetables/:id/from_json", to: "timetables#from_json", as: "from_json_timetable"
  get 'timetables_execute' => 'timetables#execute'
  get 'timetables_commit'  => 'timetables#commit', as: :timetables_commit
  resources :timetables
  resources :schedule
  resources :events
  resources :timetable_templates

end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :event, inverse_of: :attachments

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

  scope :ordering, ->{ order(:position) }
  scope :full, ->{ includes(event: :user) }

  validates :event, presence: true
  validates :position, presence: true, uniqueness: {scope: :event}, numericality: {only_integer: true}

  validates_attachment :image, presence: true, content_type: { content_type: /\Aimage/ },
                       size: { in: 0..10.megabytes }

  before_validation :set_default_position


  def set_default_position
    if self.event
      self.position ||= self.event.attachments.maximum(:position).to_i + 1
    end
    true
  end

  def edit_by?(u)
    event.edit_by?(u)
  end

  def title
    comment.present? ? comment : image_file_name
  end

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]
  before_action :check_edit, only: [:edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @attachment.update(attachment_params)
      redirect_to @attachment.post, notice: 'Вложение изменено.'
    else
      render :edit
    end
  end

  def destroy
    @attachment.destroy
    redirect_to @attachment.post, notice: 'Вложение удалено.'
  end

  private

  def set_attachment
    @attachment = Attachment.full.find(params[:id])
  end

  def attachment_params
    params.require(:attachment).permit(:image, :comment, :position)
  end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper

  def show_attachment(attachment)
    "#{attachment.image_file_name} (#{number_to_human_size(attachment.image_file_size)})"
  end

  def link_to_attachment(attachment)
    link_to(attachment.image.url, title: attachment.title, data: {toggle: 'popover', content: "#{image_tag(attachment.image.url(:thumb))}", html: true, trigger: 'hover'}) do
      concat content_tag(:span, nil, class: 'glyphicon glyphicon-paperclip')
      concat show_attachment(attachment)
    end
  end
end

app/views/attachments/_form.html.haml
= form_for @attachment do |f|
  =error_messages_for(@attachment)
  .row
    .col-md-3
      -if @attachment.image?
        =image_tag @attachment.image.url(:thumb), alt: @attachment.comment
      .form-group
        = f.label :image
        = f.file_field :image
    .col-md-3
      .form-group
        = f.label :position
        = f.number_field :position, class: 'form-control'
    .col-md-6
      .form-group
        = f.label :comment
        = f.text_field :comment, class: 'form-control'
  .actions
    = f.submit nil, class: 'btn btn-primary'

app/views/attachments/edit.html.haml
%ol.breadcrumb
  %li=link_to @attachment.post.user.name, @attachment.post.user
  %li=link_to @attachment.post.title, @attachment.post
  %li.active=show_attachment(@attachment)
.pull-right
  =link_to @attachment, data: {method: :delete, confirm: 'Вы уверены?'}, class: 'btn btn-danger' do
    %span.glyphicon.glyphicon-trash
%h1 Редактирование вложения
.clearfix

= render 'form'

app/views/attachments/index.html.haml
%h1 Listing attachments

%table
  %thead
    %tr
      %th Image
      %th Position
      %th Post
      %th Comment
      %th
      %th
      %th

  %tbody
    - @attachments.each do |attachment|
      %tr
        %td= attachment.image
        %td= attachment.position
        %td= attachment.post
        %td= attachment.comment
        %td= link_to 'Show', attachment
        %td= link_to 'Edit', edit_attachment_path(attachment)
        %td= link_to 'Destroy', attachment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Attachment', new_attachment_path

app/views/attachments/new.html.haml
%h1 New attachment

= render 'form'

= link_to 'Back', attachments_path

app/views/attachments/show.html.haml
%p#notice= notice

%p
  %b Image:
  = @attachment.image
%p
  %b Position:
  = @attachment.position
%p
  %b Post:
  = @attachment.post
%p
  %b Comment:
  = @attachment.comment

= link_to 'Edit', edit_attachment_path(@attachment)
\|
= link_to 'Back', attachments_path