config/routes.rb
Rails.application.routes.draw do

  resources :attachments
  resources :users
  get "auth/login", to: "auth#login", as: "login"
  post "auth/authentificate"
  post "auth/logout", as: "logout"
  get  "auth/logout", as: "get_logout"

  resources :menu

  root 'menu#index'
  resources :groups
  post "groups/:id/add", to: "users#add", as: "add_to_group"
  get 'groups_execute' => 'groups#execute'
  get 'groups_commit'  => 'groups#commit', as: :groups_commit

  get "timetables", to: "timetables#index", as: "timetables"
  post "events/move"
  get "timetables/init"
  post "timetables/show"
  get "timetables/:id/to_json", to: "timetables#to_json", as: "to_json_timetable"
  get "timetables/paste"
  post "timetables/:id/from_json", to: "timetables#from_json", as: "from_json_timetable"
  get 'timetables_execute' => 'timetables#execute'
  get 'timetables_commit'  => 'timetables#commit', as: :timetables_commit
  resources :timetables
  resources :schedule
  resources :events
  resources :timetable_templates

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :timetable
  belongs_to :user
  has_many :attachments, ->{ordering}, dependent: :destroy, inverse_of: :event
  attr_reader :files

  def self.create_by?(user, current_user)
    current_user && (user == current_user)
  end

  def edit_by?(u)
    self.class.create_by?(user, u)
  end

  def files=(val)
    val.each_with_index do |file, i|
      self.attachments.build(image: file, position: attachments.maximum(:position).to_i + i + 1)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  skip_before_filter :check_auth
  before_action :set_events, only: [:move, :edit, :update, :destroy]
  layout 'menu'
  def show
    if session[:user_id] != nil
      @user = User.find(session[:user_id])
    end
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    @timetable_id = params[:timetable_id]
    @date = params[:date]
    respond_to do |format|
      format.js
    end
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      respond_to do |format|
        format.js
      end
    end
  end

  def move
    @event.date = params[:date]
    @event.timetable_id = params[:timetable_id]
    @event.save
    respond_to do |format|
      format.js
    end
  end

  def edit
    @event  = Event.find(params[:id])
    @timetable_id = @event.timetable_id
    @date = @event.date
    respond_to do |format|
      format.js
    end
  end

  def update
    @event.update_attributes(event_params)
  end

  def destroy
    if @event.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  def tasks
    respond_to do |format|
      format.js
    end
  end
  private

    def set_events
      @event = Event.find(params[:id])
    end
    def event_params
      params.require(:event).permit(:name, :date, :timetable_id, :only_time, :description, files: [])
    end
end

app/views/events/_event.html.erb
<div
class='events'
data-event="<%=event.id%>">

  <% if event.only_time != nil %>
      <%=event.only_time.strftime('%H:%M')%>
  <% end %><br>
  <% if event.name != nil %>
  <%=event.name%>
  <% end %><br>
    <%= link_to edit_event_path(event), remote: true do %>
        <span class="edit">e</span>
    <% end %>
    <%= link_to event, remote: true, method: :delete,  data: { confirm: 'Удалить?' } do %>
        <span class="delete"><b>&times</b></span>
    <% end %>
      <%= link_to event_path(event), method: :get do %> <!--todo ссылка на компонент-->
          <span>Просмотр</span>
      <% end %>
</div>

app/views/events/_form.html.erb
<span class="close" id="events_close">&times</span>
<%= form_for(@event, remote: true) do |f| %>
  <p>
    <%= f.label :name, 'Название:' %>
  </p>
  <p>
    <%= f.text_field :name, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :description, 'Описание:' %>
  </p>
  <p>
    <%= f.text_field :description, class: 'form-control' %>
  </p>

  <p>
    <%= f.label :only_time, 'Время:' %>
    <%= f.time_select :only_time, class: 'form-control' %>
  </p>

  <p>
    <%= f.label :files, 'Выберите файл:' %>
  </p>

  <ol>
    <% @event.attachments.each do |attachment| %>
      <li>
        <%= link_to show_attachment(attachment), attachment.image.url %>
      </li>
    <% end %>
  </ol>
  <p>
    <%= f.file_field :files, multiple: true %>
  </p>
  <!--костыли для передачи параметра по ajax-->
  <p id="event_hidden">
    <%= f.label :timetable_id %>
    <%= f.text_field :timetable_id, options = {value: @timetable_id} %>
    <%= f.label :date %>
    <%= f.text_field :date, options = {value: @date} %>
  </p>
  <p>
    <%= f.submit('Добавить', class: 'btn btn-primary') %>
  </p>
<% end %>

app/views/events/create.js.erb
$("#addTo").append("<%= escape_javascript(render @event) %>");
$('div.events').draggable({
      containment: 'table',
      revert : 'invalid'
});
$('#addTo').removeAttr('id');

app/views/events/destroy.js.erb
$('div[data-event="<%= @event.id %>"]').remove();

app/views/events/edit.js.erb
$('#events_form').html("<%= j (render 'form') %>");
tasks($('#event_action').val());
$('#overlay').fadeIn(400,
    function () {
      $('#events_form')
          .css('display', 'block')
          .animate({opacity: 1, top: '50%'}, 200);
    });
$(".close, input[name='commit']").click(function () {
  $('#events_form')
      .animate({opacity: 0, top: '45%'}, 200,
          function () {
            $(this).css('display', 'none');
            $('#overlay').fadeOut(400);
          }
      );
});

app/views/events/new.js.erb
$('#events_form').html("<%= j (render 'form') %>");
tasks($('#event_action').val());
$('#overlay').fadeIn(400,
      function () {
  $('#events_form')
      .css('display', 'block')
      .animate({opacity: 1, top: '50%'}, 200);
});
$(".close, input[name='commit']").click(function () {
  $('#events_form')
      .animate({opacity: 0, top: '45%'}, 200,
          function () {
            $(this).css('display', 'none');
            $('#overlay').fadeOut(400);
          }
      );
});

app/views/events/show.html.erb
<p>
  <strong>Название:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Дата:</strong>
  <%= @event.only_time %>
</p>

<p>
  <strong>Описание:</strong>
  <%= @event.description %>
</p>

<% if @event.edit_by?(@user) %>
  <div class="btn-toolbar">
    <%= link_to '', edit_post_path(@event), class: 'btn btn-primary' %>
    <%= link_to '', @event, class: 'btn btn-danger', data: {method: :delete, confirm: ''} %>
  </div>
<% end %>


  <% if @event.attachments.present? %>
    <div class="panel-footer">
      <ul class="list-inline">
        <% @event.attachments.each do |attachment| %>
          <li>
            <%= link_to_attachment attachment %>
            <% if @event.edit_by?(@user) %>
              <%= link_to edit_attachment_path(attachment), class: 'text-danger' do %>
                <span class="glyphicon glyphicon-edit"></span>
              <% end %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/events/update.js.erb
$("#upd").html("<%= escape_javascript(render @event) %>");
$('div.events').draggable({
  containment: 'table',
  revert : 'invalid'
});
$('#upd').removeAttr('id');