config/routes.rb
Rails.application.routes.draw do

  resources :attachments
  resources :users
  get "auth/login", to: "auth#login", as: "login"
  post "auth/authentificate"
  post "auth/logout", as: "logout"
  get  "auth/logout", as: "get_logout"

  resources :menu

  root 'menu#index'
  resources :groups
  post "groups/:id/add", to: "users#add", as: "add_to_group"
  get 'groups_execute' => 'groups#execute'
  get 'groups_commit'  => 'groups#commit', as: :groups_commit

  get "timetables", to: "timetables#index", as: "timetables"
  post "events/move"
  get "timetables/init"
  post "timetables/show"
  get "timetables/:id/to_json", to: "timetables#to_json", as: "to_json_timetable"
  get "timetables/paste"
  post "timetables/:id/from_json", to: "timetables#from_json", as: "from_json_timetable"
  get 'timetables_execute' => 'timetables#execute'
  get 'timetables_commit'  => 'timetables#commit', as: :timetables_commit
  resources :timetables
  resources :schedule
  resources :events
  resources :timetable_templates

end

app/views/layouts/_header.html.slim
- if not @user
  nav class="top-bar"
    section class="top-bar-section"
      ul class="right"
        li
          a href="#{login_path}" Вход
        li
          a href="#{new_user_path}" Регистрация
- else
  nav class="top-bar"
    section class="top-bar-section"
      ul class="right"
        li
          a href="#{get_logout_path}" Выход
    section class="top-bar-section"
      ul class="left"
        li
          a href="#{root_path}" Главная
        li
          a href="#{ka_welcome_path}" Пройти тест
        li
          a href="#{ka_topics_path}" Редактор
        li
          a href="#{all_ka_topics_path}" Темы
        li
          a href="#{ka_questions_path}" Вопросы
        li
          a href="#{competences_path}" Компетенции
        li
          a href="#{constructs_path}" Конструкты (АМРР)
        li
          a href="#{components_path}" Компоненты
        li
          a href="#{new_ka_test_path}" Генератор
        li
          a href="#{ka_tests_path}" Тесты
        li
          a href="#{ka_results_path}" Результаты
/       li
/          a href="#{users_path}" Пользователи

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UIR</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/menu.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">

  <title>Зэк</title>

  <!--TODO: Что это?-->
  <meta name="generator" content="Bootply"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!--[if lt IE 9]>
  <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag "admin_tools", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= yield(:head) %>


  <%= csrf_meta_tags %>

</head>
<body>

<nav class="navbar navbar-brand navbar-fixed-top">
  <div class="container-fluid" id="navbar-head">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <% if @user != nil and @user.id != nil %>
        <ul class="nav navbar-nav navbar-center">
          <li><%= link_to("Главная", root_path) %></li>
          <li><%= link_to("Расписания", "/schedule") %></li>
          <li><%= link_to("Редактор", "/timetables") %></li>
          <li><%= link_to("Создать расписание", "/timetables/new") %></li>
          <li> <%= link_to("Группы", groups_path) %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">

          <li><a>
            <%= form_tag(logout_path, method: "POST") do %>
              <%= hidden_field_tag(:path, request.fullpath) %>
              <%= content_tag(:span, @user.fio) %>
              <%= submit_tag("Выход", class: 'btn btn-primary')%>
            <% end %></a></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-center">
          <li><%= link_to("Главная", root_path) %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <li> <%= link_to("Вход", login_path) %></li>
          <li> <%= link_to("Регистрация", new_user_path) %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="container" style="margin-top: 100px; width: auto;">
  <%= yield %>
</div>


<div id="footer">
  <p class="pull-right">Copyright <i class="glyphicon glyphicon-copyright-mark"></i> at DAB</p>
</div>
<div id="push"></div>
</body>
</html>